// Type declarations for Next.js static asset imports.
//
// `BrandLogo.tsx` imports the logo PNGs directly (`import logo from
// '@/public/s3k-logo.png'`), which is the supported Next.js pattern: the
// import resolves to a StaticImageData object carrying the intrinsic width
// and height, which is what lets `next/image` reserve layout space without a
// round-trip.
//
// Those module declarations normally arrive via `next-env.d.ts`, which
// references `next/image-types/global`. That file is generated by `next build`
// / `next dev` and is git-ignored (see .gitignore) — so on a clean checkout
// that runs `tsc --noEmit` *before* any build, it does not exist, and every
// image import fails with TS2307. CI hit exactly that: `npm ci` then
// `npm run typecheck`, with no build in between.
//
// Referencing the same Next-supplied types from a committed file makes the
// type check self-sufficient rather than dependent on build ordering. It adds
// no types of its own; `next-env.d.ts` regenerating on top of it is harmless,
// because both are the same reference.
/// <reference types="next" />
/// <reference types="next/image-types/global" />
