import type { NbaRecord, RegeneratedRecommendation } from './types';

/* ============================================================
   NEXT BEST ACTION — MOCK DATASET
   Frontend-only demonstration data. Every record is internally
   coherent: stage drives win probability, risk and close
   proximity drive priority, and confidence tracks how much
   supporting engagement history exists.

   All companies, people, domains and phone numbers are
   fictional. Dates are anchored to DEMO_TODAY (2026-08-07).
   ============================================================ */

export const NBA_RECORDS: NbaRecord[] = [
  {
    id: 'nba-1001',
    leadName: 'Meera Krishnan',
    leadTitle: 'VP Supply Chain',
    company: 'Northwind Logistics',
    industry: 'Logistics',
    opportunity: 'Fleet Visibility Platform — Phase 1',
    stage: 'Proposal',
    assignedTo: 'Priya Patel',
    priority: 'Critical',
    recommendation: 'Schedule commercial review with CFO within 48 hours',
    reason:
      'CFO joined the last review unannounced and asked for a three-year cost model. Proposal has been re-opened four times in six days but no commercial owner is engaged.',
    channel: 'Meeting',
    confidence: 92,
    previousAction: 'Sent revised proposal with tiered pricing',
    previousOutcome: 'Opened 4 times; pricing page viewed twice, no reply',
    nextFollowUp: '2026-08-09',
    lastCommunication: '2026-08-05',
    dealRisk: 'Medium',
    winProbability: 68,
    expectedRevenue: 480000,
    expectedCloseDate: '2026-09-18',
    email: 'meera.krishnan@northwindlogistics.example',
    phone: '+1 415 555 0182',
    leadSource: 'Inbound — Webinar',
    engagement: 'High',
    documents: 5,
    status: 'New',
    aiNotes:
      'Buying committee has widened from operations to finance. Historically this account converts within 30 days once a commercial owner is named.',
  },
  {
    id: 'nba-1002',
    leadName: 'Thomas Reinhardt',
    leadTitle: 'Director of Plant Operations',
    company: 'Vertex Manufacturing',
    industry: 'Manufacturing',
    opportunity: 'Predictive Maintenance Rollout',
    stage: 'Negotiation',
    assignedTo: 'Mike Johnson',
    priority: 'Critical',
    recommendation: 'Re-engage economic buyer before the 14 Aug budget lock',
    reason:
      'No contact with the CFO for 21 days while a competitor was named in the last call. Close date sits two days after the customer’s stated budget freeze.',
    channel: 'Call',
    confidence: 88,
    previousAction: 'Shared ROI model and reference customer deck',
    previousOutcome: 'Champion responded positively; economic buyer silent',
    nextFollowUp: '2026-08-08',
    lastCommunication: '2026-07-24',
    dealRisk: 'Critical',
    winProbability: 72,
    expectedRevenue: 725000,
    expectedCloseDate: '2026-08-16',
    email: 'thomas.reinhardt@vertexmfg.example',
    phone: '+49 30 5550 1194',
    leadSource: 'Outbound — Target Account',
    engagement: 'Moderate',
    documents: 8,
    status: 'In Progress',
    aiNotes:
      'Deal momentum has slowed from accelerating to stalled over two weeks. Competitor mention plus executive silence is the strongest churn pattern in this segment.',
  },
  {
    id: 'nba-1003',
    leadName: 'Aisha Bello',
    leadTitle: 'Head of Digital Transformation',
    company: 'Helios Financial Services',
    industry: 'Financial Services',
    opportunity: 'Client Onboarding Automation',
    stage: 'Discovery',
    assignedTo: 'Daniel Okafor',
    priority: 'High',
    recommendation: 'Schedule technical validation session with the security team',
    reason:
      'Two security questionnaires arrived within a week and the architecture lead has attended both calls. Technical validation is the gating step before a proposal.',
    channel: 'Meeting',
    confidence: 79,
    previousAction: 'Completed discovery workshop with operations',
    previousOutcome: 'Requirements confirmed; security review requested',
    nextFollowUp: '2026-08-12',
    lastCommunication: '2026-08-04',
    dealRisk: 'Low',
    winProbability: 42,
    expectedRevenue: 310000,
    expectedCloseDate: '2026-10-30',
    email: 'aisha.bello@heliosfin.example',
    phone: '+44 20 7946 0331',
    leadSource: 'Partner Referral',
    engagement: 'High',
    documents: 4,
    status: 'Scheduled',
    aiNotes:
      'Regulated buyer. Security sign-off typically adds three weeks — starting it now protects the October close date.',
  },
  {
    id: 'nba-1004',
    leadName: 'Grace Whitfield',
    leadTitle: 'Chief Nursing Informatics Officer',
    company: 'Brightpath Healthcare',
    industry: 'Healthcare',
    opportunity: 'Care Coordination Suite — 3 Hospitals',
    stage: 'Contract Review',
    assignedTo: 'Ana Ruiz',
    priority: 'High',
    recommendation: 'Confirm procurement approval timeline with legal counsel',
    reason:
      'Redlines were returned nine days ago and remain unacknowledged. Procurement has not confirmed whether the board committee meets before month end.',
    channel: 'Email',
    confidence: 84,
    previousAction: 'Returned marked-up MSA to customer counsel',
    previousOutcome: 'Acknowledged receipt; no review date committed',
    nextFollowUp: '2026-08-10',
    lastCommunication: '2026-07-29',
    dealRisk: 'Medium',
    winProbability: 88,
    expectedRevenue: 1150000,
    expectedCloseDate: '2026-08-28',
    email: 'grace.whitfield@brightpathcare.example',
    phone: '+1 617 555 0144',
    leadSource: 'Existing Account Expansion',
    engagement: 'Moderate',
    documents: 11,
    status: 'Pending',
    aiNotes:
      'Commercial terms are agreed. Remaining risk is scheduling, not substance — an explicit committee date converts this to a forecastable close.',
  },
  {
    id: 'nba-1005',
    leadName: 'Owen Marsh',
    leadTitle: 'Group Merchandising Director',
    company: 'Cobalt Retail Group',
    industry: 'Retail',
    opportunity: 'Demand Forecasting — 120 Stores',
    stage: 'Proposal',
    assignedTo: 'Grace Lim',
    priority: 'High',
    recommendation: 'Resolve the per-store pricing objection with a volume-banded quote',
    reason:
      'Two stakeholders flagged per-store licensing as the blocker on the last call. Comparable accounts closed after moving to a banded model.',
    channel: 'Proposal',
    confidence: 81,
    previousAction: 'Presented proposal to merchandising leadership',
    previousOutcome: 'Positive on capability; explicit pricing objection raised',
    nextFollowUp: '2026-08-11',
    lastCommunication: '2026-08-03',
    dealRisk: 'Medium',
    winProbability: 61,
    expectedRevenue: 545000,
    expectedCloseDate: '2026-09-25',
    email: 'owen.marsh@cobaltretail.example',
    phone: '+44 161 555 0277',
    leadSource: 'Inbound — Website',
    engagement: 'High',
    documents: 6,
    status: 'New',
    aiNotes:
      'Objection is structural, not budgetary. Total contract value is unlikely to fall if the unit of pricing changes.',
  },
  {
    id: 'nba-1006',
    leadName: 'Elena Duarte',
    leadTitle: 'Head of Grid Analytics',
    company: 'Lumen Energy Partners',
    industry: 'Energy',
    opportunity: 'Asset Performance Analytics',
    stage: 'Qualification',
    assignedTo: 'Rahul Menon',
    priority: 'Medium',
    recommendation: 'Run a 30-minute discovery call to confirm budget ownership',
    reason:
      'Strong technical interest from an individual contributor, but no budget holder has been identified across three touchpoints.',
    channel: 'Call',
    confidence: 58,
    previousAction: 'Sent capability overview after inbound enquiry',
    previousOutcome: 'Replied with technical questions; commercial scope unclear',
    nextFollowUp: '2026-08-13',
    lastCommunication: '2026-08-01',
    dealRisk: 'Medium',
    winProbability: 22,
    expectedRevenue: 190000,
    expectedCloseDate: '2026-11-27',
    email: 'elena.duarte@lumenenergy.example',
    phone: '+34 91 555 0163',
    leadSource: 'Inbound — Content Download',
    engagement: 'Moderate',
    documents: 2,
    status: 'New',
    aiNotes:
      'Confidence is limited by thin engagement history. Treat the value estimate as indicative until a budget owner is confirmed.',
  },
  {
    id: 'nba-1007',
    leadName: 'Victor Almeida',
    leadTitle: 'Managing Director, Operations',
    company: 'Aureus Capital',
    industry: 'Financial Services',
    opportunity: 'Portfolio Reporting Modernisation',
    stage: 'Negotiation',
    assignedTo: 'Daniel Okafor',
    priority: 'Critical',
    recommendation: 'Send revised proposal with the phased-payment option before Friday',
    reason:
      'Procurement accepted scope but pushed back on year-one cash outlay. A phased structure was requested verbatim on the 2 Aug call.',
    channel: 'Proposal',
    confidence: 90,
    previousAction: 'Negotiation call with procurement and operations',
    previousOutcome: 'Scope agreed; payment schedule to be restructured',
    nextFollowUp: '2026-08-07',
    lastCommunication: '2026-08-02',
    dealRisk: 'Low',
    winProbability: 79,
    expectedRevenue: 860000,
    expectedCloseDate: '2026-09-04',
    email: 'victor.almeida@aureuscapital.example',
    phone: '+65 6555 0119',
    leadSource: 'Existing Account Expansion',
    engagement: 'High',
    documents: 9,
    status: 'In Progress',
    aiNotes:
      'The customer articulated the exact commercial change required. Delay, not disagreement, is the main remaining risk.',
  },
  {
    id: 'nba-1008',
    leadName: 'Sanjay Iyer',
    leadTitle: 'Chief Agronomy Officer',
    company: 'Trellis Agritech',
    industry: 'Agritech',
    opportunity: 'Yield Intelligence Pilot',
    stage: 'Discovery',
    assignedTo: 'Rahul Menon',
    priority: 'Medium',
    recommendation: 'Share the pilot success framework and agree measurable exit criteria',
    reason:
      'Customer is enthusiastic but has not defined what a successful pilot looks like. Undefined pilots in this segment convert at roughly half the rate.',
    channel: 'Content',
    confidence: 71,
    previousAction: 'Ran product deep-dive with the agronomy team',
    previousOutcome: 'Positive reception; pilot scope discussed informally',
    nextFollowUp: '2026-08-14',
    lastCommunication: '2026-08-06',
    dealRisk: 'Medium',
    winProbability: 38,
    expectedRevenue: 145000,
    expectedCloseDate: '2026-11-13',
    email: 'sanjay.iyer@trellisagri.example',
    phone: '+91 80 5550 0148',
    leadSource: 'Conference — AgriTech Summit',
    engagement: 'High',
    documents: 3,
    status: 'New',
    aiNotes:
      'Engagement quality is high and recent. The gap is commercial structure rather than interest.',
  },
  {
    id: 'nba-1009',
    leadName: 'Claire Fontaine',
    leadTitle: 'Programme Director',
    company: 'Kestrel Aerospace',
    industry: 'Aerospace',
    opportunity: 'Supplier Quality Analytics',
    stage: 'Proposal',
    assignedTo: 'Mike Johnson',
    priority: 'High',
    recommendation: 'Provide the implementation timeline requested on the 31 Jul call',
    reason:
      'The programme office asked for a week-by-week deployment plan and has not been sent one. Proposal review is blocked on that document.',
    channel: 'Content',
    confidence: 86,
    previousAction: 'Proposal walkthrough with programme office',
    previousOutcome: 'Implementation timeline explicitly requested',
    nextFollowUp: '2026-08-08',
    lastCommunication: '2026-07-31',
    dealRisk: 'Medium',
    winProbability: 64,
    expectedRevenue: 620000,
    expectedCloseDate: '2026-10-09',
    email: 'claire.fontaine@kestrelaero.example',
    phone: '+33 1 55 55 0126',
    leadSource: 'Outbound — Target Account',
    engagement: 'Moderate',
    documents: 7,
    status: 'Pending',
    aiNotes:
      'A specific, small deliverable is blocking a large deal. Cost of the action is low relative to the exposure.',
  },
  {
    id: 'nba-1010',
    leadName: 'Marcus Lindqvist',
    leadTitle: 'VP Guest Experience',
    company: 'Meridian Hospitality',
    industry: 'Hospitality',
    opportunity: 'Unified Guest Profile',
    stage: 'Qualification',
    assignedTo: 'Ana Ruiz',
    priority: 'Low',
    recommendation: 'Send the hospitality benchmark report and propose a Q4 revisit',
    reason:
      'Customer confirmed budget is committed until October. Low-touch nurture protects the relationship without consuming pipeline focus.',
    channel: 'Email',
    confidence: 54,
    previousAction: 'Introductory call with guest experience team',
    previousOutcome: 'Interested but no budget in the current period',
    nextFollowUp: '2026-09-08',
    lastCommunication: '2026-07-21',
    dealRisk: 'Low',
    winProbability: 18,
    expectedRevenue: 125000,
    expectedCloseDate: '2026-12-11',
    email: 'marcus.lindqvist@meridianhospitality.example',
    phone: '+46 8 555 0173',
    leadSource: 'Inbound — Webinar',
    engagement: 'Low',
    documents: 1,
    status: 'Pending',
    aiNotes:
      'Timing is the constraint, not fit. Re-scoring is recommended once the new budget period opens.',
  },
  {
    id: 'nba-1011',
    leadName: 'Dr. Ingrid Sørensen',
    leadTitle: 'Head of Clinical Data',
    company: 'Solace Pharma',
    industry: 'Pharmaceuticals',
    opportunity: 'Trial Data Harmonisation',
    stage: 'Negotiation',
    assignedTo: 'Priya Patel',
    priority: 'High',
    recommendation: 'Schedule a validation workshop with quality assurance before signature',
    reason:
      'QA raised a computer-system-validation question that legal cannot resolve. Unanswered validation questions have delayed two comparable deals by a quarter.',
    channel: 'Meeting',
    confidence: 83,
    previousAction: 'Contract terms call with legal and procurement',
    previousOutcome: 'Terms broadly agreed; QA validation question raised',
    nextFollowUp: '2026-08-10',
    lastCommunication: '2026-08-04',
    dealRisk: 'Medium',
    winProbability: 76,
    expectedRevenue: 940000,
    expectedCloseDate: '2026-09-30',
    email: 'ingrid.sorensen@solacepharma.example',
    phone: '+45 33 55 0157',
    leadSource: 'Partner Referral',
    engagement: 'High',
    documents: 10,
    status: 'Scheduled',
    aiNotes:
      'Technical assurance rather than commercial negotiation is the critical path here.',
  },
  {
    id: 'nba-1012',
    leadName: 'Rebecca Hollins',
    leadTitle: 'Head of Claims Transformation',
    company: 'Ironclad Insurance',
    industry: 'Insurance',
    opportunity: 'Claims Triage Automation',
    stage: 'Proposal',
    assignedTo: 'Grace Lim',
    priority: 'Critical',
    recommendation: 'Follow up on the proposal within 24 hours — 16 days of silence',
    reason:
      'No response since the proposal was sent on 22 Jul despite three document opens. Silence after engagement is the strongest early churn signal in this dataset.',
    channel: 'Call',
    confidence: 74,
    previousAction: 'Sent full proposal with implementation estimate',
    previousOutcome: 'Opened 3 times; no reply to two follow-up emails',
    nextFollowUp: '2026-08-08',
    lastCommunication: '2026-07-22',
    dealRisk: 'High',
    winProbability: 52,
    expectedRevenue: 415000,
    expectedCloseDate: '2026-09-11',
    email: 'rebecca.hollins@ironcladins.example',
    phone: '+1 312 555 0198',
    leadSource: 'Outbound — Target Account',
    engagement: 'Low',
    documents: 5,
    status: 'New',
    aiNotes:
      'Document engagement continues while replies have stopped, which usually indicates an internal review rather than disengagement. A call outperforms a fourth email.',
  },
  {
    id: 'nba-1013',
    leadName: 'Kenji Watanabe',
    leadTitle: 'Network Strategy Lead',
    company: 'Bluepeak Telecom',
    industry: 'Telecom',
    opportunity: 'Network Assurance Platform',
    stage: 'Discovery',
    assignedTo: 'Rahul Menon',
    priority: 'Medium',
    recommendation: 'Map the buying committee — only one of five stakeholders is engaged',
    reason:
      'Single-threaded on a technical lead with no access to the network operations director who owns the budget.',
    channel: 'Internal',
    confidence: 66,
    previousAction: 'Technical discovery session with network engineering',
    previousOutcome: 'Strong technical fit; no exposure to leadership',
    nextFollowUp: '2026-08-12',
    lastCommunication: '2026-07-30',
    dealRisk: 'High',
    winProbability: 35,
    expectedRevenue: 680000,
    expectedCloseDate: '2026-11-06',
    email: 'kenji.watanabe@bluepeaktel.example',
    phone: '+81 3 5555 0184',
    leadSource: 'Conference — Telecom World',
    engagement: 'Moderate',
    documents: 3,
    status: 'New',
    aiNotes:
      'Deal size is significant relative to stakeholder coverage. Broadening access is higher value than advancing the technical conversation.',
  },
  {
    id: 'nba-1014',
    leadName: 'Patricia Nwosu',
    leadTitle: 'Group Head of Projects',
    company: 'Granite Construction Group',
    industry: 'Construction',
    opportunity: 'Project Cost Intelligence',
    stage: 'Contract Review',
    assignedTo: 'Mike Johnson',
    priority: 'Medium',
    recommendation: 'Confirm signature authority and circulate the countersigned order form',
    reason:
      'Legal review is complete and the sponsor has verbally approved. The only open item is which entity signs.',
    channel: 'Email',
    confidence: 91,
    previousAction: 'Final legal review call',
    previousOutcome: 'All redlines closed; verbal approval given',
    nextFollowUp: '2026-08-09',
    lastCommunication: '2026-08-05',
    dealRisk: 'Low',
    winProbability: 92,
    expectedRevenue: 390000,
    expectedCloseDate: '2026-08-21',
    email: 'patricia.nwosu@graniteconstruct.example',
    phone: '+27 11 555 0135',
    leadSource: 'Partner Referral',
    engagement: 'High',
    documents: 9,
    status: 'In Progress',
    aiNotes:
      'Highest-confidence record in the current set: recent contact, closed legal review and explicit verbal commitment.',
  },
  {
    id: 'nba-1015',
    leadName: 'Julian Reyes',
    leadTitle: 'Director of Audience Analytics',
    company: 'Halcyon Media',
    industry: 'Media',
    opportunity: 'Audience Intelligence Workspace',
    stage: 'Proposal',
    assignedTo: 'Ana Ruiz',
    priority: 'Medium',
    recommendation: 'Share the media-sector ROI case study ahead of the 13 Aug review',
    reason:
      'The sponsor must justify spend to a sceptical finance partner and asked for comparable outcomes in the same sector.',
    channel: 'Content',
    confidence: 77,
    previousAction: 'Proposal review with analytics leadership',
    previousOutcome: 'Supportive; internal business case being prepared',
    nextFollowUp: '2026-08-11',
    lastCommunication: '2026-08-04',
    dealRisk: 'Medium',
    winProbability: 57,
    expectedRevenue: 265000,
    expectedCloseDate: '2026-10-02',
    email: 'julian.reyes@halcyonmedia.example',
    phone: '+1 213 555 0166',
    leadSource: 'Inbound — Website',
    engagement: 'High',
    documents: 4,
    status: 'New',
    aiNotes:
      'The champion is doing the selling internally. Supplying evidence is more effective than adding meetings.',
  },
  {
    id: 'nba-1016',
    leadName: 'Fiona Blackwood',
    leadTitle: 'Director of Student Systems',
    company: 'Pinewood Education Trust',
    industry: 'Education',
    opportunity: 'Student Lifecycle Analytics',
    stage: 'Discovery',
    assignedTo: 'Grace Lim',
    priority: 'Low',
    recommendation: 'Send the data-protection overview requested by the governance lead',
    reason:
      'A single outstanding document is holding the governance review. No commercial risk indicators are present.',
    channel: 'Email',
    confidence: 69,
    previousAction: 'Requirements call with student systems team',
    previousOutcome: 'Requirements captured; governance pack requested',
    nextFollowUp: '2026-08-18',
    lastCommunication: '2026-08-01',
    dealRisk: 'Low',
    winProbability: 33,
    expectedRevenue: 98000,
    expectedCloseDate: '2026-11-20',
    email: 'fiona.blackwood@pinewoodtrust.example',
    phone: '+44 131 555 0142',
    leadSource: 'Inbound — Content Download',
    engagement: 'Moderate',
    documents: 2,
    status: 'Pending',
    aiNotes:
      'Small deal with a clean path. Low priority reflects value, not health.',
  },
  {
    id: 'nba-1017',
    leadName: 'Dmitri Sokolov',
    leadTitle: 'Head of Connected Vehicle',
    company: 'Zephyr Mobility',
    industry: 'Automotive',
    opportunity: 'Telematics Data Platform',
    stage: 'Negotiation',
    assignedTo: 'Daniel Okafor',
    priority: 'High',
    recommendation: 'Counter the competitor’s data-residency claim with the regional hosting brief',
    reason:
      'The customer repeated a competitor’s claim that regional hosting is unavailable. Leaving it unanswered through a negotiation cycle is the main loss risk.',
    channel: 'Content',
    confidence: 80,
    previousAction: 'Commercial negotiation call',
    previousOutcome: 'Pricing acceptable; competitor differentiation raised',
    nextFollowUp: '2026-08-10',
    lastCommunication: '2026-08-03',
    dealRisk: 'High',
    winProbability: 70,
    expectedRevenue: 1020000,
    expectedCloseDate: '2026-09-19',
    email: 'dmitri.sokolov@zephyrmobility.example',
    phone: '+48 22 555 0129',
    leadSource: 'Outbound — Target Account',
    engagement: 'High',
    documents: 8,
    status: 'In Progress',
    aiNotes:
      'Factually incorrect competitor positioning is correctable. Speed matters more than depth of response.',
  },
  {
    id: 'nba-1018',
    leadName: 'Laura Nkemdirim',
    leadTitle: 'Head of Process Safety',
    company: 'Silverline Chemicals',
    industry: 'Chemicals',
    opportunity: 'Process Safety Monitoring',
    stage: 'Qualification',
    assignedTo: 'Priya Patel',
    priority: 'Medium',
    recommendation: 'Qualify against the compliance deadline before committing pre-sales effort',
    reason:
      'A regulatory deadline was mentioned but not dated. Effort allocation depends on whether it falls inside this fiscal year.',
    channel: 'Call',
    confidence: 61,
    previousAction: 'Initial qualification call',
    previousOutcome: 'Compliance driver identified; timeline undefined',
    nextFollowUp: '2026-08-13',
    lastCommunication: '2026-08-02',
    dealRisk: 'Medium',
    winProbability: 26,
    expectedRevenue: 220000,
    expectedCloseDate: '2026-12-04',
    email: 'laura.nkemdirim@silverlinechem.example',
    phone: '+1 713 555 0151',
    leadSource: 'Inbound — Webinar',
    engagement: 'Moderate',
    documents: 2,
    status: 'New',
    aiNotes:
      'Compliance-driven deals compress quickly once a date is known. The qualifying question is worth more than a demo at this stage.',
  },
  {
    id: 'nba-1019',
    leadName: 'Hannah Bergström',
    leadTitle: 'Director of Lab Operations',
    company: 'Orchid BioLabs',
    industry: 'Biotech',
    opportunity: 'Lab Throughput Optimisation',
    stage: 'Proposal',
    assignedTo: 'Rahul Menon',
    priority: 'High',
    recommendation: 'Rebuild the business case around throughput, not headcount savings',
    reason:
      'The customer rejected the headcount-reduction framing on the last call and reframed the goal as sample throughput.',
    channel: 'Proposal',
    confidence: 78,
    previousAction: 'Business case presentation to lab leadership',
    previousOutcome: 'Value framing challenged; capability not questioned',
    nextFollowUp: '2026-08-12',
    lastCommunication: '2026-08-05',
    dealRisk: 'Medium',
    winProbability: 59,
    expectedRevenue: 355000,
    expectedCloseDate: '2026-10-16',
    email: 'hannah.bergstrom@orchidbiolabs.example',
    phone: '+46 31 555 0187',
    leadSource: 'Conference — BioProcess Europe',
    engagement: 'High',
    documents: 5,
    status: 'New',
    aiNotes:
      'The objection is to the narrative rather than the product. Re-framing typically recovers probability within one cycle.',
  },
  {
    id: 'nba-1020',
    leadName: 'Ahmed Rahimi',
    leadTitle: 'Fleet Director',
    company: 'Fathom Marine Services',
    industry: 'Marine',
    opportunity: 'Vessel Performance Monitoring',
    stage: 'Discovery',
    assignedTo: 'Mike Johnson',
    priority: 'Low',
    recommendation: 'Re-engage after the dry-dock window closes in September',
    reason:
      'The customer is operationally unavailable until mid-September and asked explicitly to be contacted afterwards.',
    channel: 'Email',
    confidence: 52,
    previousAction: 'Discovery call with fleet operations',
    previousOutcome: 'Good fit confirmed; customer requested a September revisit',
    nextFollowUp: '2026-09-16',
    lastCommunication: '2026-07-18',
    dealRisk: 'Low',
    winProbability: 31,
    expectedRevenue: 175000,
    expectedCloseDate: '2026-12-18',
    email: 'ahmed.rahimi@fathommarine.example',
    phone: '+971 4 555 0175',
    leadSource: 'Partner Referral',
    engagement: 'Low',
    documents: 2,
    status: 'Dismissed',
    aiNotes:
      'Dismissed by the account owner because the customer set an explicit re-contact date. Scheduled for automatic re-scoring in September.',
  },
  {
    id: 'nba-1021',
    leadName: 'Simone Delacroix',
    leadTitle: 'Head of Asset Management',
    company: 'Vantage Property Group',
    industry: 'Real Estate',
    opportunity: 'Portfolio Performance Dashboard',
    stage: 'Proposal',
    assignedTo: 'Ana Ruiz',
    priority: 'Medium',
    recommendation: 'Add the second portfolio to scope before the proposal is finalised',
    reason:
      'The sponsor mentioned a second portfolio twice in the last meeting. Expanding scope pre-signature avoids a separate procurement cycle.',
    channel: 'Proposal',
    confidence: 73,
    previousAction: 'Solution review with asset management team',
    previousOutcome: 'Positive; adjacent portfolio mentioned unprompted',
    nextFollowUp: '2026-08-14',
    lastCommunication: '2026-08-06',
    dealRisk: 'Low',
    winProbability: 63,
    expectedRevenue: 285000,
    expectedCloseDate: '2026-09-29',
    email: 'simone.delacroix@vantageproperty.example',
    phone: '+33 4 55 55 0192',
    leadSource: 'Existing Account Expansion',
    engagement: 'High',
    documents: 4,
    status: 'New',
    aiNotes:
      'Expansion signal detected from repeated unprompted mentions. Estimated uplift is roughly 40% of current deal value.',
  },
  {
    id: 'nba-1022',
    leadName: 'Robert Achebe',
    leadTitle: 'Head of Network Operations',
    company: 'Copperfield Utilities',
    industry: 'Utilities',
    opportunity: 'Outage Prediction Programme',
    stage: 'Negotiation',
    assignedTo: 'Grace Lim',
    priority: 'High',
    recommendation: 'Escalate the stalled security review to the customer’s CISO sponsor',
    reason:
      'The security review has been open for 23 days with no assigned reviewer, while the close date is six weeks away.',
    channel: 'Internal',
    confidence: 76,
    previousAction: 'Submitted security questionnaire and architecture pack',
    previousOutcome: 'Received; no reviewer assigned in 23 days',
    nextFollowUp: '2026-08-08',
    lastCommunication: '2026-07-27',
    dealRisk: 'High',
    winProbability: 71,
    expectedRevenue: 790000,
    expectedCloseDate: '2026-09-22',
    email: 'robert.achebe@copperfieldutil.example',
    phone: '+44 121 555 0139',
    leadSource: 'Outbound — Target Account',
    engagement: 'Moderate',
    documents: 7,
    status: 'Pending',
    aiNotes:
      'Process stall rather than commercial resistance. Escalation is low-risk because the champion remains supportive.',
  },
  {
    id: 'nba-1023',
    leadName: 'Yuki Tanaka',
    leadTitle: 'VP Platform Engineering',
    company: 'Nimbus Cloudworks',
    industry: 'Technology',
    opportunity: 'Observability Consolidation',
    stage: 'Closed Won',
    assignedTo: 'Daniel Okafor',
    priority: 'Medium',
    recommendation: 'Open the managed-services upsell conversation at the 30-day review',
    reason:
      'The deal closed on 24 Jul and adoption is ahead of plan. Post-implementation reviews are the highest-converting upsell moment in this segment.',
    channel: 'Meeting',
    confidence: 85,
    previousAction: 'Completed onboarding kickoff with platform team',
    previousOutcome: 'Deployment ahead of schedule; sponsor highly engaged',
    nextFollowUp: '2026-08-24',
    lastCommunication: '2026-08-06',
    dealRisk: 'Low',
    winProbability: 100,
    expectedRevenue: 240000,
    expectedCloseDate: '2026-10-23',
    email: 'yuki.tanaka@nimbuscloudworks.example',
    phone: '+81 6 5555 0111',
    leadSource: 'Existing Account Expansion',
    engagement: 'High',
    documents: 6,
    status: 'Completed',
    aiNotes:
      'Expected revenue reflects the follow-on managed-services opportunity, not the closed contract.',
  },
  {
    id: 'nba-1024',
    leadName: 'Isabel Moreno',
    leadTitle: 'Supply Chain Director',
    company: 'Sable Foods International',
    industry: 'Food & Beverage',
    opportunity: 'Cold Chain Visibility',
    stage: 'Qualification',
    assignedTo: 'Priya Patel',
    priority: 'Medium',
    recommendation: 'Book a 20-minute scoping call on the spoilage-cost baseline',
    reason:
      'The customer quoted an annual spoilage figure but no measurement baseline exists. Establishing it early anchors the business case.',
    channel: 'Call',
    confidence: 64,
    previousAction: 'Responded to inbound enquiry with case studies',
    previousOutcome: 'Engaged; requested a scoping conversation',
    nextFollowUp: '2026-08-11',
    lastCommunication: '2026-08-04',
    dealRisk: 'Medium',
    winProbability: 29,
    expectedRevenue: 205000,
    expectedCloseDate: '2026-11-30',
    email: 'isabel.moreno@sablefoods.example',
    phone: '+52 55 5555 0168',
    leadSource: 'Inbound — Website',
    engagement: 'Moderate',
    documents: 3,
    status: 'New',
    aiNotes:
      'Early stage but a quantified pain statement is already present, which is a positive qualification signal.',
  },
];

/* ------------------------------------------------------------
   Alternate recommendations used by the local "Regenerate"
   demo action. Keyed by deal stage so the replacement stays
   commercially sensible for the selected record.
   ------------------------------------------------------------ */

export const REGENERATION_POOL: Record<string, RegeneratedRecommendation[]> = {
  Qualification: [
    {
      recommendation: 'Confirm budget ownership with a 20-minute qualification call',
      reason:
        'Technical interest is established but no budget holder has been named. Confirming ownership is the cheapest way to test whether this deal is real.',
      confidence: 62,
      priority: 'Medium',
      channel: 'Call',
      aiNotes:
        'Re-scored on qualification completeness. Confidence stays moderate until a commercial owner is identified.',
    },
    {
      recommendation: 'Send the sector maturity assessment and invite a scoping session',
      reason:
        'A low-commitment diagnostic gives the buyer a reason to bring colleagues into the conversation.',
      confidence: 57,
      priority: 'Low',
      channel: 'Content',
      aiNotes:
        'Nurture-weighted recommendation. Suitable when the account has no active budget cycle.',
    },
  ],
  Discovery: [
    {
      recommendation: 'Map the buying committee and request an introduction to the budget owner',
      reason:
        'Engagement is concentrated in one function. Broadening stakeholder coverage raises win rate more than additional product depth at this stage.',
      confidence: 70,
      priority: 'High',
      channel: 'Internal',
      aiNotes: 'Re-scored on stakeholder coverage rather than activity recency.',
    },
    {
      recommendation: 'Schedule a technical validation session with the architecture team',
      reason:
        'Repeated technical questions indicate the evaluation has moved past capability into feasibility.',
      confidence: 75,
      priority: 'High',
      channel: 'Meeting',
      aiNotes: 'Re-scored on the volume and specificity of inbound technical questions.',
    },
  ],
  Proposal: [
    {
      recommendation: 'Send a written summary of agreed value with a decision timeline request',
      reason:
        'Proposal engagement is present but unstructured. Asking for a decision date converts interest into a forecastable step.',
      confidence: 79,
      priority: 'High',
      channel: 'Email',
      aiNotes: 'Re-scored with emphasis on document engagement and reply latency.',
    },
    {
      recommendation: 'Offer a scoped pilot to de-risk the first phase of the commitment',
      reason:
        'Deal size relative to account maturity suggests commitment risk. A phased entry point protects the larger opportunity.',
      confidence: 72,
      priority: 'Medium',
      channel: 'Proposal',
      aiNotes: 'Alternative path weighted toward reducing perceived buyer risk.',
    },
  ],
  Negotiation: [
    {
      recommendation: 'Request a joint close plan with named owners and dates',
      reason:
        'Terms are broadly agreed but the path to signature is undocumented, which is where deals of this size typically slip.',
      confidence: 84,
      priority: 'Critical',
      channel: 'Meeting',
      aiNotes: 'Re-scored on close-date proximity and the absence of a mutual action plan.',
    },
    {
      recommendation: 'Escalate to executive sponsor to unblock the outstanding internal review',
      reason:
        'An internal process — not commercial disagreement — is the binding constraint on the close date.',
      confidence: 80,
      priority: 'High',
      channel: 'Internal',
      aiNotes: 'Alternative path weighted toward process risk rather than pricing.',
    },
  ],
  'Contract Review': [
    {
      recommendation: 'Confirm signature authority and circulate the execution-ready order form',
      reason:
        'Legal review is closed. The remaining variable is administrative, and removing it protects the forecast month.',
      confidence: 89,
      priority: 'High',
      channel: 'Email',
      aiNotes: 'Re-scored on redline closure and verbal commitment signals.',
    },
    {
      recommendation: 'Agree an implementation start date to lock the commercial timeline',
      reason:
        'Anchoring delivery dates gives the customer an operational reason to complete signature this month.',
      confidence: 86,
      priority: 'Medium',
      channel: 'Meeting',
      aiNotes: 'Alternative path weighted toward delivery momentum.',
    },
  ],
  'Closed Won': [
    {
      recommendation: 'Run a 30-day value review and capture a reference commitment',
      reason:
        'Adoption is ahead of plan. Early advocacy is easiest to secure while the implementation is still visible internally.',
      confidence: 82,
      priority: 'Medium',
      channel: 'Meeting',
      aiNotes: 'Re-scored on post-sale adoption telemetry rather than pipeline signals.',
    },
    {
      recommendation: 'Introduce the adjacent business unit through the executive sponsor',
      reason:
        'A satisfied sponsor is the highest-converting route into a second business unit.',
      confidence: 78,
      priority: 'Medium',
      channel: 'Internal',
      aiNotes: 'Expansion-weighted alternative for accounts already in delivery.',
    },
  ],
  'Closed Lost': [
    {
      recommendation: 'Schedule a win/loss debrief with the evaluation sponsor',
      reason:
        'Structured loss reviews are the most reliable source of competitive positioning intelligence.',
      confidence: 68,
      priority: 'Low',
      channel: 'Meeting',
      aiNotes: 'Re-scored for learning value rather than revenue potential.',
    },
  ],
};
