"""Single source of truth for SQLAlchemy metadata used by Alembic.

``migrations/env.py`` imports :data:`target_metadata` from here, guaranteeing
that migrations are autogenerated from exactly the same metadata the runtime
maps against.

When a Platform or CRM module gains a ``models.py``, import it below. The
import is what registers the tables on :class:`~app.core.database.Base`; a
model that is not imported here is invisible to ``alembic revision
--autogenerate``.
"""

from __future__ import annotations

from sqlalchemy import MetaData

from app.core.database import Base

# --- Model registrations (none yet) ----------------------------------------
# As modules gain tables, import their models module here, for example:
#
#     from app.platform.organizations import models as organization_models
#     from app.products.crm.accounts import models as account_models
#
# and list the imported names in __all__ so linters see them as re-exported.
#
# No models exist yet by design: authentication, tenant and CRM tables are out
# of scope for this task.

target_metadata: MetaData = Base.metadata

__all__ = ["Base", "target_metadata"]
